# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04test\"(\n\nAddRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\" \n\rDecodeRequest\x12\x0f\n\x07ImgData\x18\x01 \x01(\t\"6\n\x0e\x44\x65\x63odeResponse\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x11\n\tTimestamp\x18\x02 \x01(\t\"3\n\x11\x46\x61\x63\x65\x44\x65tectRequest\x12\x0f\n\x07ImgData\x18\x01 \x01(\t\x12\r\n\x05TrxID\x18\x02 \x01(\t\"7\n\x12\x46\x61\x63\x65\x44\x65tectResponse\x12\r\n\x05TrxID\x18\x01 \x01(\t\x12\x12\n\nEmbeddings\x18\x02 \x01(\t2\xb6\x01\n\x0cTestResponse\x12,\n\x03\x41\x64\x64\x12\x10.test.AddRequest\x1a\x11.test.AddResponse\"\x00\x12\x35\n\x06\x44\x65\x63ode\x12\x13.test.DecodeRequest\x1a\x14.test.DecodeResponse\"\x00\x12\x41\n\nFaceDetect\x12\x17.test.FaceDetectRequest\x1a\x18.test.FaceDetectResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=20
  _globals['_ADDREQUEST']._serialized_end=60
  _globals['_ADDRESPONSE']._serialized_start=62
  _globals['_ADDRESPONSE']._serialized_end=91
  _globals['_DECODEREQUEST']._serialized_start=93
  _globals['_DECODEREQUEST']._serialized_end=125
  _globals['_DECODERESPONSE']._serialized_start=127
  _globals['_DECODERESPONSE']._serialized_end=181
  _globals['_FACEDETECTREQUEST']._serialized_start=183
  _globals['_FACEDETECTREQUEST']._serialized_end=234
  _globals['_FACEDETECTRESPONSE']._serialized_start=236
  _globals['_FACEDETECTRESPONSE']._serialized_end=291
  _globals['_TESTRESPONSE']._serialized_start=294
  _globals['_TESTRESPONSE']._serialized_end=476
# @@protoc_insertion_point(module_scope)
